version: "3.9"
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "wp_nscreen"
      MYSQL_USER: "wp_admin"
      MYSQL_PASSWORD: "password"

  nscreen:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wp_nscreen
      WORDPRESS_DB_USER: wp_admin
      WORDPRESS_DB_PASSWORD: password

volumes:
  db_data:
